import turtle
color_1 = ['orange', 'white', 'green']
t = turtle.Pen()
t.hideturtle()
t.penup()

t.goto(-125, 89)
t.showturtle()
t.pendown()
t.width(1)
turtle.bgcolor('black')
for i in range(15):
    t.pencolor(color_1[0])
    t.fd(250)
    t.rt(90)
    t.fd(2)
    t.rt(90)
    t.fd(250)
    t.lt(90)
    t.fd(2)
    t.lt(90)
for i in range(15):
    t.pencolor(color_1[1])
    t.fd(250)
    t.rt(90)
    t.fd(2)
    t.rt(90)
    t.fd(250)
    t.lt(90)
    t.fd(2)
    t.lt(90)
for i in range(15):
    t.pencolor(color_1[2])
    t.fd(250)
    t.rt(90)
    t.fd(2)
    t.rt(90)
    t.fd(250)
    t.lt(90)
    t.fd(2)
    t.lt(90)
t.hideturtle()
t.penup()
t.goto(-100, 60)
t.showturtle()
t.pendown()
turtle.turtlesize(3)
turtle.color('navy')
turtle.shape('circle')
t.hideturtle()
turtle.mainloop()
